
spring:
  messages:
    basename: messages, errors

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/projectb?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234

#  main:
#    allow-bean-definition-overriding: true

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: on_param
    include-stacktrace: on_param
    include-binding-errors: on_param